const syntax = {
  "init": true,
  "method": true,
  "run": true,
  "math": true,
  "print.cons": true,
  "print.count": true,
  "print.stime": true,
  "print.etime": true,
  "print.clear": true,
  "print.warn": true,
  "print.info": true,
  "print.error": true,
  "edit.round": true,
  "edit.floor": true,
  "edit.ceil": true,
  "edit.flip": true,
  "edit.abs": true,
  "edit.del": true,
  "construct.list": true,
  "construct.map": true,
  "index.list": true,
  "index.map": true,
  "set.random": true,
  "set.min": true,
  "set.max": true,
  "set.sqr": true,
  "if": true,
  "end": true,
};

export default syntax;
